name: Deploy to EC2 on Push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to EC2
        run: |
          rsync -avz --exclude=".git" --exclude="node_modules" ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}

      - name: Build frontend and restart backend on EC2
        run: |
          HOST=${{ secrets.EC2_HOST }}
          USER=${{ secrets.EC2_USER }}
          PATH_ON_EC2=${{ secrets.EC2_PATH }}

          ssh $USER@$HOST <<'EOF'
            cd $PATH_ON_EC2

            # Ensure Node.js is installed (you may skip if already done)
            if ! command -v node &> /dev/null; then
              curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi

            # Install PM2 if not already installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            
            ls
            cd attendance
            cd frontend && npm install && npm run build && cd ..
            sudo cp -r frontend/dist/* /usr/share/nginx/html/
            ls
            cd backend && npm install
            pm2 restart all || pm2 start server.js
