name: Deploy to EC2 on Push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to EC2
        run: |
          rsync -avz --exclude=".git" --exclude="node_modules" ./ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.EC2_PATH }}

      - name: Build frontend and restart backend on EC2
        run: |
          HOST=${{ secrets.EC2_HOST }}
          USER=${{ secrets.EC2_USER }}
          PATH_ON_EC2=${{ secrets.EC2_PATH }}

          ssh $USER@$HOST <<EOF
          set -e
          cd $PATH_ON_EC2

          cd frontend
          npm ci
          npm run build
          sudo cp -r build/* /usr/share/nginx/html/
          cd ..

          cd backend
          npm ci

          if pm2 describe my-app > /dev/null; then
            pm2 restart my-app
          else
            pm2 start app.js --name my-app
          fi
EOF
